---
  title: "Discussion & Conclusions"
---
  
When analyzing the data against a few crime variables, a few interesting observations were made. 

**Comparing murder rates in 2010 with stopped African Americans who were frisked in 2011** 

This analysis revealed that there was a significant effect for stopped African Americans frisks in the year 2011 based on the murder rates from 2010. The p-value for an African American being stopped/frisked was 0.0349 and the p-value for an African American being stopped/frisked based on the murder rates of 2010 was <2e-16. Therefore, one could infer that based on the murder rates in 2010, the likelihood of being stopped/frisked if African American in 2011, was significantly greater than the previous years. 

**Comparing murder rates in 2010 with stopped females who were frisked in 2011** 

This analysis revealed two significant p-values for this regression. The regression looked at murder rates from the year 2010 and compared them to the amount of female stops/frisks in the year following the murder rates. The p-value for females stopped and frisked in 2011 was 6.46e-09 and the p-value for the females stopped and frisked in 2011 to the murder rates in 2010 was 2.25e-11. Based on ths analysis, it appears as if the rate at which females were stopped/frisked went up based on the murder rates in the previous years. 

**Comparing murder rates and robbery rates in 2010 with stopped African Americans who were frisked in 2011**

This analysis compared murder and robbery data from 2010 to the magnitude of African Americans that were stopped in 2011. There was only a significant effect for the murder rates and the African Americans stopped/frisked showing a p-value of 2.25e-10. Therefore, the robbery data from the year 2010 had no effect on the number of blacks stopped in the year 2011, but the murder rates did. 

**Comparing murder rates and robbery rates in 2010 with stopped young adults who were frisked in 2011** 

This analysis looked at murder and robbery data from 2010 against the stopped/frisked young adults in 2011. Ages which qualified for an individual that was stopped were anyone the age of 30 or younger. There was a significant effect for the robbery rates in 2010 and the young stopped adults in 2011 revealing a p-value of 1.9e-09. Looking at this data, one would infer that younger individuals were stopped/frisked after the robbery rates in 2010 due to assumptions that young people may have been committing the robbberies. 

**Comparing murder rates, robbery rates, and felony assault rates in 2010 with stopped African Americans who were frisked in 2011** 

The analysis here compares three forms of crimes in 2010 with stopped African Americans in 2011. There was only a significant effect for murder rates alongside African Americans who were frisked the following year. The p-value from this was 6.26e-08. This shows that the murder rates in 2010 would reveal that the amount of African Americans being stopped/frisked the following year goes up. 

**Comparing murder rates, robbery rates, and felony assault rates in 2010 with stopped young people who were frisked in 2011** 

This analysis looked at the amount of individuals that are the age of 30 or younger, who were stopped/frisked in 2011 compared to the previous years crime data of murder, robbery, and felony assault rates. The results show that there was only one significant effect. This significance was only for felony assault rates and stopped young adults who were frisked. Essentially, this means that the rate of felony assaults in the year 2010, correlated with the amount of young adults (<=30) who were stopped/frisked in the year 2011 in New York City. 


